config:
    soundboard:
        sampleBaseDirectory: samples

    slim:
        settings:
            displayErrorDetails: true

    router:
        routes:
            samples_list:
                path: /samples
                controller: TeamThyme\Soundboard\Controllers\SamplesController
                action: listAction
                methods: [ GET ]
            samples_get:
                path: /samples/{file:.+}
                controller: TeamThyme\Soundboard\Controllers\SamplesController
                action: getAction
                methods: [ GET ]
            telegram:
                path: /telegram
                controller: TeamThyme\Soundboard\Controllers\TelegramController
                action: webhookAction
                methods: [ POST ]
