name: CI
on:
  push:
    branches:
      # TODO: Enable for all branches once frontend rewrite is merged
      - frontend-rewrite
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Run Jest tests
        run: yarn test
      - name: Run TypeScript type checker
        run: yarn test:types
